spring.application.name=ecom-application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc.postgresql.//localhost.5432/ecomdb
spring.datasource.username=datab
spring.datasource.password=datab
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dilect.PostgreSQLDialect
