spring:

    application:
        name: ecom-application

    datasource:
        url: jdbc:postgresql://localhost:5432/ecomdb
        username: embarkx
        password: embarkx




    jpa:
#        database: POSTGRESQL
        show-sql: true

        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect